// dupe
export const ADD_POST = 'ADD_POST'
export const UPDATE_NEW_POST_TEXT = 'UPDATE_NEW_POST_TEXT'
export const UPDATE_NEW_MESSAGE_BODY = 'UPDATE_NEW_MESSAGE_BODY'
export const SEND_MESSAGE = 'SEND_MESSAGE'
export const FOLLOW_BUTTON = 'FOLLOW_BUTTON'
export const UNFOLLOW_BUTTON = 'NFOLLOW_BUTTON'
export const SET_USERS = 'SET_USERS'

